theme:
  name: material
  highlightjs: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  logo: favicon.ico
  favicon: favicon.ico
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

  # palette:
    # primary: blue grey
  font:
    text: Open Sans
    code: Fira Code
  features:
    - navigation.footer
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

repo_name: ujwalnk/MachineLearning101
repo_url: https://github.com/ujwalnk/MachineLearning101
site_name: MachineLearning101
site_url: https://ujwalnk.github.io/MachineLearning101

nav:
  - Intro: index.md
  - Machine Learning:
    - Machine Learning/Data Preprocessing.md
    - Machine Learning/Model to be used.md
    - Machine Learning/Random Forest Classifier.md
    - Machine Learning/SGD Classifier.md
  - Neural Networks:
    - Neural Networks/Data Preprocessing.md
    - Neural Networks/Image Recognition.md
  - Deep Dives:
    - Deep Dives/FPGA for Machine Learning.md
    - Deep Dives/Model Persistance.md
  - Examples:
    - (ML) SGD Classifier: examples/Machine_Learning_01_Weather_Classfication.ipynb
    - (ML) Random Forest Classifier: examples/Machine_Learning_02_Weather_Classfication.ipynb
    - (ML) Random Forest & SGD Regressor: examples/Machine_Learning_01_Weather_Classfication.ipynb
    - (NN) Image Classifier: examples/Neural_Network_01_Image_Classification.ipynb

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
        - class: mermaid
        - format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter